[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "osbn"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
webbrowser = "0.7"
tiny_http = "0.12"
url = "2"
